# http://docs.travis-ci.com/user/languages/go/
language: go

go: 1.5

os:
  - linux
  - osx

matrix:
  include:
    - env: git-latest
      os: linux
      addons:
        apt:
          sources:
          - git-core
          packages:
          - git
    - env: git-latest
      os: osx
      # The 'before_install' phase cannot be used here as we would override the
      # default 'before_install' phase. The 'before_script' phase is sufficient
      # for the Git install since the Git binary is only used in the tests.
      before_script:
        - >
          brew update;
          brew install git;

before_install:
  - repo=`basename $PWD`; localDir=`dirname $PWD`; cfDir="`dirname $localDir`/github"
  - if [[ "$localDir" != "$cfDir" ]]; then mv "$localDir" "$cfDir"; cd ../../github/$repo; export TRAVIS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/$repo; fi
  - export GIT_LFS_TEST_DIR="$localDir/git-lfs-tests"

install: true

script: script/cibuild

notifications:
  email: false
