version: 2

jobs:
  bootstrap:
    macos:
      xcode: "9.2.0"
    working_directory: ~
    steps:
      - run: git clone https://github.com/git-lfs/git-lfs.git ~/git-lfs
      - run: echo 'export GOPATH=~/git-lfs/.go' >> $BASH_ENV
      - run: brew update
      - run: brew prune
      - run: brew upgrade go || brew install go
      - run: brew upgrade git || brew install git
      - run: brew upgrade gettext || brew install gettext
      - run: git clone https://github.com/git/git.git ~/git-lfs/git-source
      - run: go get -d -v github.com/spf13/cobra
      - run: go get -d -v github.com/ThomsonReutersEikon/go-ntlm/ntlm
      - run: mkdir -p ~/git-lfs/.go/src/github.com/git-lfs
      - run: ln -s ~/git-lfs ~/git-lfs/.go/src/github.com/git-lfs
      - save_cache:
          key: git-lfs-{{ .Branch }}-{{ .Revision }}
          paths:
            - /usr/local/Cellar
            - ~/git-lfs

  build_with_system_git:
    macos:
      xcode: "9.2.0"
    working_directory: ~/git-lfs
    environment:
      GIT_SOURCE_REPO: https://github.com/git/git.git
    steps:
      - restore_cache:
          key: git-lfs-{{ .Branch }}-{{ .Revision }}
      - run: echo go git gettext | xargs brew link --force
      - run: echo 'export GOPATH=~/go' >> $BASH_ENV
      - run: echo 'export GIT_LFS_TEST_DIR=~/git-lfs-tests' >> $BASH_ENV
      - run: echo 'export PATH=$GOPATH/bin:$PATH' >> $BASH_ENV
      - run: pwd && ./script/integration

  build_with_earliest_supported_git:
    macos:
      xcode: "9.2.0"
    working_directory: ~/git-lfs
    environment:
      GIT_EARLIEST_SUPPORTED_VERSION: v2.0.0
      GIT_SOURCE_REPO: https://github.com/git/git.git
    steps:
      - restore_cache:
          key: git-lfs-{{ .Branch }}-{{ .Revision }}
      - run: echo go git gettext | xargs brew link --force
      - run:
          command: ./script/install-git-source "$GIT_EARLIEST_SUPPORTED_VERSION"
          environment:
            NO_OPENSSL: YesPlease
            APPLE_COMMON_CRYPTO: YesPlease
      - run: echo 'export GOPATH=~/go' >> $BASH_ENV
      - run: echo 'export GIT_LFS_TEST_DIR=~/git-lfs-tests' >> $BASH_ENV
      - run: echo 'export PATH=$GOPATH/bin:$PATH' >> $BASH_ENV
      - run: pwd && ./script/integration

  build_with_latest_git:
    macos:
      xcode: "9.2.0"
    working_directory: ~/git-lfs
    environment:
      GIT_LATEST_SOURCE_BRANCH: master
      GIT_SOURCE_REPO: https://github.com/git/git.git
    steps:
      - restore_cache:
          key: git-lfs-{{ .Branch }}-{{ .Revision }}
      - run: echo go git gettext | xargs brew link --force
      - run:
          command: ./script/install-git-source "$GIT_LATEST_SOURCE_BRANCH"
          environment:
            NO_OPENSSL: YesPlease
            APPLE_COMMON_CRYPTO: YesPlease
      - run: echo 'export GOPATH=~/go' >> $BASH_ENV
      - run: echo 'export GIT_LFS_TEST_DIR=~/git-lfs-tests' >> $BASH_ENV
      - run: echo 'export PATH=$GOPATH/bin:$PATH' >> $BASH_ENV
      - run: pwd && ./script/integration

workflows:
  version: 2
  build:
    jobs:
      - bootstrap
      - build_with_earliest_supported_git:
          requires:
            - bootstrap
      - build_with_latest_git:
          requires:
            - bootstrap
      - build_with_system_git:
          requires:
            - bootstrap
